// Replay file format and runner.
#include <doctest/doctest.h>

#include <string>

#include "core/Replay.h"
#include "test_sim_helpers.h"

using namespace gd;
using namespace simtest;

namespace {

bool hasError(const std::vector<std::string>& errs, const std::string& needle) {
    for (const auto& e : errs)
        if (e.find(needle) != std::string::npos) return true;
    return false;
}

std::vector<std::string> parseErrors(const std::string& text) {
    std::vector<std::string> errs;
    auto r = parseReplay(text, errs);
    CHECK_FALSE(r.has_value());
    CHECK_FALSE(errs.empty());
    return errs;
}

}  // namespace

TEST_CASE("replay: parses the documented example") {
    const std::string text =
        "gdreplay 1\n"
        "level 3\n"
        "tickrate 240\n"
        "press 120\n"
        "release 130\n"
        "press 400\n"
        "end 11000\n";
    std::vector<std::string> errs;
    auto r = parseReplay(text, errs);
    REQUIRE(r.has_value());
    CHECK(errs.empty());
    CHECK(r->level == 3);
    CHECK(r->tickRate == 240);
    REQUIRE(r->inputs.size() == 3);
    CHECK(r->inputs[0].tick == 120);
    CHECK(r->inputs[0].press);
    CHECK(r->inputs[1].tick == 130);
    CHECK_FALSE(r->inputs[1].press);
    CHECK(r->inputs[2].tick == 400);
    CHECK(r->endTick == 11000);
}

TEST_CASE("replay: comments, blank lines and whitespace are allowed") {
    const std::string text =
        "# generated by gd_solve\n"
        "\n"
        "gdreplay 1   # header\n"
        "  level 2\n"
        "tickrate\t240\n"
        "press 0\n"
        "end 5 # done\n";
    std::vector<std::string> errs;
    auto r = parseReplay(text, errs);
    REQUIRE(r.has_value());
    CHECK(r->inputs.size() == 1);
    CHECK(r->endTick == 5);
}

TEST_CASE("replay: strict errors carry line numbers") {
    CHECK(hasError(parseErrors(""), "missing 'gdreplay 1'"));
    CHECK(hasError(parseErrors("level 1\n"), "line 1: first item must be 'gdreplay 1'"));
    CHECK(hasError(parseErrors("gdreplay 2\n"), "line 1: unsupported replay version"));
    CHECK(hasError(parseErrors("gdreplay 1\nlevel 1\ntickrate 60\nend 10\n"), "line 3: tickrate must be 240"));
    CHECK(hasError(parseErrors("gdreplay 1\nlevel 1\ntickrate 240\npress 10\npress 20\nend 30\n"),
                   "line 5: press while already held"));
    CHECK(hasError(parseErrors("gdreplay 1\nlevel 1\ntickrate 240\nrelease 10\nend 30\n"),
                   "line 4: release while not held"));
    CHECK(hasError(parseErrors("gdreplay 1\nlevel 1\ntickrate 240\npress 10\nrelease 10\nend 30\n"),
                   "line 5: tick 10 must be greater than previous tick 10"));
    CHECK(hasError(parseErrors("gdreplay 1\nlevel 1\ntickrate 240\npress 50\nend 30\n"),
                   "line 5: tick 30 must be greater"));
    CHECK(hasError(parseErrors("gdreplay 1\nlevel 1\ntickrate 240\njump 5\nend 30\n"),
                   "line 4: unknown keyword 'jump'"));
    CHECK(hasError(parseErrors("gdreplay 1\nlevel 1\ntickrate 240\npress 5x\nend 30\n"),
                   "line 4: '5x' is not an integer"));
    CHECK(hasError(parseErrors("gdreplay 1\nlevel 1\ntickrate 240\npress 5 6\nend 30\n"),
                   "line 4: expected '<keyword> <integer>'"));
    CHECK(hasError(parseErrors("gdreplay 1\nlevel 1\ntickrate 240\nend 30\npress 40\n"),
                   "line 5: nothing may follow 'end'"));
    CHECK(hasError(parseErrors("gdreplay 1\nlevel 1\nlevel 2\ntickrate 240\nend 30\n"),
                   "line 3: duplicate 'level'"));
    CHECK(hasError(parseErrors("gdreplay 1\nlevel 1\ntickrate 240\npress -1\nend 30\n"),
                   "line 4: tick must be >= 0"));
    const auto missing = parseErrors("gdreplay 1\npress 3\n");
    CHECK(hasError(missing, "line 3: missing 'level'"));
    CHECK(hasError(missing, "missing 'tickrate'"));
    CHECK(hasError(missing, "missing 'end'"));
}

TEST_CASE("replay: write then parse round-trips") {
    Replay r;
    r.level = 7;
    r.tickRate = phys::kTickRate;
    r.inputs = {{0, true}, {3, false}, {100, true}, {250, false}};
    r.endTick = 9000;
    const std::string text = writeReplay(r);
    std::vector<std::string> errs;
    auto back = parseReplay(text, errs);
    REQUIRE(back.has_value());
    CHECK(back->level == 7);
    CHECK(back->endTick == 9000);
    REQUIRE(back->inputs.size() == r.inputs.size());
    for (size_t i = 0; i < r.inputs.size(); ++i) {
        CHECK(back->inputs[i].tick == r.inputs[i].tick);
        CHECK(back->inputs[i].press == r.inputs[i].press);
    }
    CHECK(writeReplay(*back) == text);
}

TEST_CASE("replay: held script <-> replay conversion") {
    const auto script = lcgScript(2000, 5);
    const Replay r = replayFromHeld(1, script, 2000);
    const auto back = heldPerTick(r);
    REQUIRE(back.size() == script.size());
    CHECK(back == script);
    for (size_t i = 1; i < r.inputs.size(); ++i) CHECK(r.inputs[i].tick > r.inputs[i - 1].tick);
}

TEST_CASE("replay: runReplay wins, dies, or times out") {
    Level L = makeLevel(40, {spike(20)});
    // Find a winning tap, as a solver would.
    int win = -1;
    for (int jt = 0; jt < 600 && win < 0; ++jt) {
        Sim sim(L);
        run(sim, 10000, tapAt(jt));
        if (sim.won()) win = jt;
    }
    REQUIRE(win >= 0);
    Replay r;
    r.level = 0;
    r.tickRate = phys::kTickRate;
    r.inputs = {{win, true}, {win + 1, false}};
    r.endTick = 2000;
    ReplayResult res = runReplay(L, r);
    CHECK(res.won);
    CHECK_FALSE(res.died);
    CHECK(res.x + phys::kPlayerSize >= L.endX);

    // Same through the text format.
    std::vector<std::string> errs;
    auto parsed = parseReplay(writeReplay(r), errs);
    REQUIRE(parsed.has_value());
    const ReplayResult res2 = runReplay(L, *parsed);
    CHECK(res2.won);
    CHECK(res2.tick == res.tick);
    CHECK(res2.x == res.x);

    // End tick too early: timeout, not a win.
    r.endTick = res.tick - 1;
    res = runReplay(L, r);
    CHECK_FALSE(res.won);
    CHECK_FALSE(res.died);
    CHECK(res.tick == r.endTick);

    // No input: dies on the spike.
    r.inputs.clear();
    r.endTick = 2000;
    res = runReplay(L, r);
    CHECK(res.died);
    CHECK_FALSE(res.won);
}
